# Creator: Eddy Elbrink
# Project: Inethi Network
# Container: ownCloud with MariaDB/MySQL
#
# ownCloud URL = "http://localhost:8081"
#
# Initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: owncloud
# Database name: owncloud
# Database host: replace "localhost" with "mysql"

version: '2'

services:

  owncloud:
    image: owncloud
    container_name: owncloud-server
    domainname: owncloud.inethi.net
    hostname: owncloud
    volumes:
      - /mnt/data/owncloud/apps:/var/www/html/apps
      - /mnt/data/owncloud/config:/var/www/html/config
      - /mnt/data/owncloud/data:/var/www/html/data
    ports:
      - 8081:80
    depends_on:
      - mysql
    links:
      - mysql
    restart: on-failure
    network_mode: "bridge"

  mysql:
    image: mariadb
    container_name: owncloud-mysql
    domainname: mysql.inethi.net
    hostname: mysql
    volumes:
      - /mnt/data/owncloud/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
    restart: on-failure
    network_mode: "bridge"
    